package dev.rustdroid.ide.ui.theme

import androidx.compose.ui.graphics.Color

// Brand: Rust orange on warm charcoal, Material 3 tonal.
val RustOrange = Color(0xFFF7770F)
val RustOrangeDim = Color(0xFF8A4308)
val Charcoal = Color(0xFF1C1B1F)

val md_dark_primary = RustOrange
val md_dark_onPrimary = Color(0xFFFFFFFF)
val md_dark_primaryContainer = Color(0xFF7A3A00)
val md_dark_onPrimaryContainer = Color(0xFFFFDCC2)
val md_dark_secondary = Color(0xFFE2BFA8)
val md_dark_onSecondary = Color(0xFF3E2C1E)
val md_dark_secondaryContainer = Color(0xFF57402F)
val md_dark_onSecondaryContainer = Color(0xFFFFDCC2)
val md_dark_tertiary = Color(0xFFA6CB9E)
val md_dark_onTertiary = Color(0xFF113913)
val md_dark_error = Color(0xFFFFB4AB)
val md_dark_onError = Color(0xFF690005)
val md_dark_errorContainer = Color(0xFF93000A)
val md_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_dark_background = Color(0xFF191714)
val md_dark_onBackground = Color(0xFFEDE0D4)
val md_dark_surface = Color(0xFF191714)
val md_dark_onSurface = Color(0xFFEDE0D4)
val md_dark_surfaceVariant = Color(0xFF4D4539)
val md_dark_onSurfaceVariant = Color(0xFFD0C4B4)
val md_dark_outline = Color(0xFF998F7F)

val md_light_primary = RustOrangeDim
val md_light_onPrimary = Color(0xFFFFFFFF)
val md_light_primaryContainer = Color(0xFFFFDBC8)
val md_light_onPrimaryContainer = Color(0xFF2C1500)
val md_light_secondary = Color(0xFF77574A)
val md_light_onSecondary = Color(0xFFFFFFFF)
val md_light_secondaryContainer = Color(0xFFFFDBC8)
val md_light_onSecondaryContainer = Color(0xFF2C1500)
val md_light_tertiary = Color(0xFF4A6544)
val md_light_onTertiary = Color(0xFFFFFFFF)
val md_light_error = Color(0xFFBA1A1A)
val md_light_onError = Color(0xFFFFFFFF)
val md_light_errorContainer = Color(0xFFFFDAD6)
val md_light_onErrorContainer = Color(0xFF410002)
val md_light_background = Color(0xFFFFF8F4)
val md_light_onBackground = Color(0xFF201A16)
val md_light_surface = Color(0xFFFFF8F4)
val md_light_onSurface = Color(0xFF201A16)
val md_light_surfaceVariant = Color(0xFFEDE0D4)
val md_light_onSurfaceVariant = Color(0xFF4D4539)
val md_light_outline = Color(0xFF7F7567)
